### ISSUE TITLE
Implement shopt -s autocd

### ISSUE THREAD

**Issue by andychu** [oils-for-unix/oils#1971]
https://oilshell.zulipchat.com/#narrow/stream/264891-oil-help/topic/autocd.20doesn't.20seem.20to.20work

**Comment by mcepl** [comment]
This is still failed with 0.22.0.

**Comment by andychu** [comment]
Hm are you using this?  Interested in writing some failing spec tests for it?

Here's an example commit from the last release:

https://github.com/oilshell/oil/commit/659935488d79e39705e4c4454c2d116d3bc018c3

https://github.com/oilshell/oil/wiki/Spec-Tests

**Comment by mcepl** [comment]
Just what's shown in that zulip chat: running
```sh
 $ shopt -s autocd
 $ cd
 $ /tmp
 $ [ $(pwd) == "/tmp" ] ; echo $?
```

**Comment by mcepl** [comment]
And obviously it does:

```
 $ shopt -s autocd
 $ /tmp
  /tmp
  ^
[ interactive ]:2: Can't execute '/tmp': Permission denied
 $
```

**Comment by mcepl** [comment]
Apparently too complicated?

**Comment by andychu** [comment]
I am not sure if this is complicated or not 

Generally there is an extreme long tail of bash features, especially `shopt`

One criteria is if we can make more programs run

- https://github.com/oils-for-unix/oils/wiki/Shell-Programs-That-Run-Under-OSH

Does `autocd` make "unlock" any major programs?  Right now I'm not aware of any

---

Another way to get it prioritized is to add failing spec tests:

https://github.com/oils-for-unix/oils/wiki/Spec-Tests

The tests  can be merged before any implementation

---

This has worked in the past -- one person adds spec tests, and another person does the implementation.  (And of course sometimes it's the same person)

**Comment by mcepl** [comment]
> Does `autocd` make "unlock" any major programs? Right now I'm not aware of any

Not that I am aware of. It is only about using oils for the interactive work.

Do you use oils for interactive work? Is oils meant to be used for interactive work, or it is just yet another tiny POSIX-like scripting language?

My idea was to replace fish as my console with a POSIX-like shell, which however (comparing to bash) is actively developed.

Unfortunately, it seems to me that oils is not that, but just a gateway drug to projects you are actually interested in (`ysh` and perhaps even some other language).

I have now even find your explicit statement that `oils` is not meant to compete with `fish` and that somebody else has to write a useful interactive frontend for it, because you are not interested in it.

> Another way to get it prioritized is to add failing spec tests:

I have just written that above, if your project is so complicated, that you, its owner, cannot copy & paste those few lines somewhere and make them work easily, it is too complicated for me to study it.

**Comment by andychu** [comment]
`autocd` can be probably  easily be added to Oils, but I don't have time to do it

Also you don't appear to understand how open source works

I'll just leave this here - https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9

This issue is depressing me, so I'll just close it too

Maybe someone will come along later and request the feature again, maybe not

**Comment by mcepl** [comment]
> Also you don't appear to understand how open source works

First Linux was Red Hat Linux 6.0 (KDE before 1.0, Gnome was then completely useless), since 2006 working for Red Hat, now at SUSE. Sure, I have no idea how open source works.

And no, I was not demanding you do anything. “[…] ask not what your country can do for you — ask what you can do for your country.”

I was just testing what are your priorities in developing the project, and how much you care for the interactive use, and how much I would suffer if using `oils` as my interactive shell, and how much thus I should invest in helping you. The answer seems to be that we have different ideas, so I will look somewhere else. Nothing against anybody.

Live long and prosper!
